- udata_gouvfr/tests.py
- udata_gouvfr/views.py
Export udata-gouvfr specifics URLs to the sitemap.
Connects to etalab/udata#46
> Added sitemap for udata-gouvfr specific URLs

- udata_gouvfr/views.py
This pull request add a `static_url_path` parameter to the blueprint to avoid url resolution conflicts with the main app.
> Use static_url_path to avoid static conflict on blueprint

- udata_gouvfr/theme/templates/subnav-large.html
- udata_gouvfr/theme/templates/subnav-small.html
- udata_gouvfr/theme/templates/topic/subnav.html
That's the correct way in English and given that we use the label for integration tests I want those to be perennial.
> Remove white spaces before punctuation, refs #153

- migrations/2015-09-28-fix-maaf-harvester-doublouns.js
- udata_gouvfr/harvesters/maaf.py
This pull request fix the maff harvester avoiding to create doublons.
It requires the provided migration first to work.
> Fix maaf harvester

- udata_gouvfr/theme/templates/header.html
Fix for https://github.com/etalab/udata/issues/227.
See https://github.com/etalab/udata/compare/etalab:master...vinyll:227-use-organization-acronym for changes to apply.
> display organization.accronym or title in the header dropdown menu. fix #227

- udata_gouvfr/views.py
This PR ensure the C3 et dataconnexions pages only dispay visible objects (datasets and/or reuses)
> Hide deleted datasets and reuses form C3 and dataconnexions pages

- theme/img/logo-colophon.md
- theme/img/logo-header.svg
Original:
Using the Fira Sans font:
Back to the Century Gothic Std (bold):
With the end like [gouvernement.fr](http://www.gouvernement.fr/) but without the capslock:
With the HTML tag like the [forum](https://forum.etalab.gouv.fr/):
> Improve the logo, fix etalab/udata#360

- theme/less/gouvfr.less
- udata_gouvfr/theme/templates/home.html
- udata_gouvfr/theme/theme.py
This PR display latest forum topics on home page (include demo feedback)
This is optionnal and use the following settings:
* `DISCOURSE_URL` *(required)*: the remote Discourse instance base URL
* `DISCOURSE_CATEGORY_ID`: an optionnal category ID to limit topics from
* `DISCOURSE_LISTING_TYPE`: the listing type, one of `latest`, `top` or `new`. Default to `latest`
* `DISCOURSE_LISTING_LIMIT`: the amount of topics to fetch and display.
> Display last forum topics on home page

- udata_gouvfr/theme/templates/dataset/display.html
- udata_gouvfr/theme/templates/reuse/display.html
Replaces hard-coded references to Datagouv with SITE_AUTHOR from the config.
This complements https://github.com/etalab/udata/pull/443
In practice, this is only used in the header of the community contributions, for the dataset and reuse pages.
> Use site author instead of hardcoded text

- circle.yml
Dev branch now relies on Elasticsearch 2.4
> Use Elasticsearch 2.4.1 on dev branch

- udata_gouvfr/harvesters/maaf.py
This PR make use of Dublin Core frequencies in MAAF Harvester (see opendatateam/udata#631)
> Map MAAF Harvester frequencies to  Dublin Core ones

- circle.yml
- circleci-requirements.sh
- circleci.dev.pip
- circleci.master.pip
Change a little bit the build:
- use published packaged only (was already started)
- same requirements for dev/master but use pre version of udata on dev
- no more requirement files
> No more git udata repository download, use published packages

- CHANGELOG.md
- package.json
- theme/less/gouvfr-dataset.less
- theme/less/gouvfr-post.less
- theme/less/gouvfr-reuse.less
- theme/less/gouvfr.less
- theme/less/gouvfr/buttons.less
- theme/less/gouvfr/mixins.less
- theme/less/gouvfr/navbars.less
- udata_gouvfr/templates/c3.html
- udata_gouvfr/templates/nec_mergitur.html
- udata_gouvfr/templates/openfield16.html
- udata_gouvfr/theme/templates/header.html
- udata_gouvfr/theme/templates/home.html
- udata_gouvfr/theme/templates/subnav-large.html
- udata_gouvfr/theme/templates/subnav-small.html
- udata_gouvfr/theme/templates/topic/subnav.html
This PR is the gouvfr theme part of opendatateam/udata#869:
- upgrade to latest bootstrap 3.3.7
- drop some unused classes (`.icon-left`...)
- remove all Glyphicons reference and use only font-awesome
> Split bootstrap style

- CHANGELOG.md
- udata_gouvfr/templates/licences.html
- udata_gouvfr/tests.py
- udata_gouvfr/theme/theme.py
- udata_gouvfr/views.py
Ajout d'une page /licences explicitant les articles D.323-2-1 et D.323-2-2 du code des relations entre le public et l’administration (CRPA) sur les licences de réutilisation des informations publiques, et listant les licences homologuées par Etalab le 5 mai 2017.
> Add new licences page

- theme/less/gouvfr/navbars.less
- udata_gouvfr/theme/templates/subnav-small.html
Vertically centers fields in search bar and fix side alignments.
Depends on https://github.com/opendatateam/udata/pull/996
> improve(search): fix alignments of the search bar

- CHANGELOG.md
- theme/less/gouvfr-dataset.less
- theme/less/gouvfr-reuse.less
This PR fixes some little spacing issues.
**before**
**after**
**before**
**after**
**before**
**after**
> Fix some spacing issues

- udata_gouvfr/theme/templates/footer.html
This PR is workaround for a translation collision on "contact":
- the action "contact" translates to "Contacter"
- the contact section in this theme footer translates to "Contact".
As Jinja does not support `pgettext` (see pallets/jinja#441), there is no proper way to differenciate the 2 string.
So this workaround switch the footer section name to the plural form "Contacts" (it is a list of contact point)
> Fix translations collision on contact

- CHANGELOG.md
- udata_gouvfr/migrations/2017-08-04-fix-wrong-spatial-coverages.js
This PRs fix some wrong spatial coverages, side-effect of the early spatial completer.
The different cases are:
- French "Arrondissement", "Canton" or "Iris" instead of french town => replaced by the right town
- Selected all zones composing another zone => replaced by the full zone
- Unpublished dataset for testing purpose => zone is pulled, we don't try to find the right equivalent
The resulting zones can then be properly migrated by `udata territories migrate_zone_ids`.
See also opendatateam/udata#1080
> Fix some wrong spatial coverages

- README.md
need to do a npm install in udata-gouvfr before launching inv assets-build and not inv assets_build.
took it from udata documentation http://udata.readthedocs.io/en/stable/development-environment/, not sure about the impact
> correction installation doc

- CHANGELOG.md
- udata_gouvfr/__init__.py
- udata_gouvfr/tests.py
- udata_gouvfr/theme/templates/subnav-small.html
Following https://github.com/opendatateam/udata/pull/1164, this uses the new `search` blueprint.
> New search blueprint

- .circleci/requirements.pip
- CHANGELOG.md
- theme/less/gouvfr.less
- theme/less/gouvfr/navbars.less
This PR moves CSS dropdown behaviors to `udata` core (see opendatateam/udata#1297)
> Remove the common dropdown style behavior

- package.json
- tasks.py
- theme/less/gouvfr/community.less
- webpack.config.js
This PR fix the current assets broken build and ensure false positive does not happen anymore (bad behavior in webpack 1.x, webpack/webpack#708)
> Fix assets false positives

- theme/js/dataset-recommendations.js
Show the recommendations block only when everything is bootstrapped. In case of an error higher up in the process, it should not be displayed at all, which is good.
Refs opendatateam/udata#1329
> Differ showing recommendations block

- CHANGELOG.md
- theme/less/gouvfr/community.less
- theme/less/gouvfr/resources.less
This PR move some style to `udata` core.
Connected to opendatateam/udata#1393
> Move discussion indent to udata and fix border styling on threads

- theme/less/gouvfr/community.less
This PR remove the extra padding on community resources.
> Remove extra padding on community resources and discussions

- .gitignore
- requirements/install.pip
- requirements/test.pip
- udata_gouvfr/tests.py
This PR migrate test to pure pytest syntax (enabling use of `fixtures` and other pytest features)
(Requires some changes in opendatateam/udata#1428)
> Migrate test to pure pytest and plugin usage

- .circleci/config.yml
- udata_gouvfr/tests.py
Ensure test pass when user as a local `WP_ATOM_URL` or `DISCOURSE_URL` config
> Fix test config

- CHANGELOG.md
- theme/less/gouvfr-admin.less
- theme/less/gouvfr.less
- theme/less/gouvfr/cards.less
- theme/less/gouvfr/community.less
- theme/less/gouvfr/resources.less
- theme/less/gouvfr/variables.less
This PR follow changes from opendatateam/udata#1460
| Before | After |
|----------|--------|
| ![screenshot-data xps-2018 02 21-20-09-46](https://user-images.githubusercontent.com/15725/36501109-8b924bea-1746-11e8-8e4c-585779aae3eb.png) | ![screenshot-data xps-2018 02 21-20-12-45](https://user-images.githubusercontent.com/15725/36501119-9237da1e-1746-11e8-9af7-c18bad7ef0ab.png) |
| Before | After |
|----------|--------|
| ![screenshot-data xps-2018 02 21-20-10-18](https://user-images.githubusercontent.com/15725/36501125-95efcf36-1746-11e8-8033-02f3bb8a2ade.png) | ![screenshot-data xps-2018 02 21-20-12-10](https://user-images.githubusercontent.com/15725/36501127-9810169a-1746-11e8-8469-35773213e26d.png) |
Fix style to match cards size
| Before | After |
|----------|--------|
| …
> Remove useless style and adapt new reuse add card

- .circleci/config.yml
- CHANGELOG.md
- udata_gouvfr/templates/c3.html
- udata_gouvfr/templates/dataconnexions-5.html
- udata_gouvfr/templates/dataconnexions-6.html
- udata_gouvfr/templates/nec_mergitur.html
- udata_gouvfr/templates/openfield16.html
- udata_gouvfr/templates/spd.html
- udata_gouvfr/theme/templates/home.html
This PR fixes some cards positionning
| Before | After |
|----------|--------|
| ![screenshot-data xps-2018 03 14-14-32-40](https://user-images.githubusercontent.com/15725/37405487-0897242c-2795-11e8-9c46-ad9372de27a8.png) | ![screenshot-data xps-2018 03 14-14-34-02](https://user-images.githubusercontent.com/15725/37405493-0be40280-2795-11e8-8c0c-096313a57b8a.png) |
> Fixes some cards positionning

- CHANGELOG.md
- theme/js/dataset-recommendations.js
- theme/less/gouvfr-dataset-recommendations.less
- theme/less/oembed.less
- theme/oembed.js
- udata_gouvfr/theme/templates/dataset/display.html
- udata_gouvfr/theme/templates/oembed.html
- webpack.config.js
This PR:
Connects to opendatateam/udata#1525
> Switch to new OEmbed

- CHANGELOG.md
- theme/less/gouvfr-dataset.less
Drop the not so visible non-certified custom style on datasets pages.
> Drop non-certified style

- CHANGELOG.md
- theme/less/gouvfr/modals.less
This PR remove the hard-coded modal width and so fixes modals with `modal-lg` class width.
> Fix modal-lg width

- CHANGELOG.md
- theme/less/gouvfr.less
- theme/less/gouvfr/suivi.less
- udata_gouvfr/templates/suivi.html
- udata_gouvfr/theme/__init__.py
- udata_gouvfr/views.py
This is almost identical to https://beta.gouv.fr/suivi/, which I find 👌.
I renamed Piwik to Matomo and updated the links.
I removed
> de la majorité de nos produits, dont beta.gouv.fr
I think we can also remove this sentence, which may not have the adequate "tone" for our site:
> C’est vrai, vous n’avez pas eu à cliquer sur un bloc qui recouvre la moitié de la page pour dire que vous êtes d’accord avec le dépôt de cookies — même si vous ne savez pas ce que ça veut dire !
@ThomasMenant, is this page OK from a legal point of view?
> Add "suivi" page

- CHANGELOG.md
- udata_gouvfr/templates/spd.html
La page SPD ne listait que l'article du CRPA et le décret, il manquait l'arrêté.
> Ajout de l'arrêté SPD du 14 juin 2017

- CHANGELOG.md
- theme/less/gouvfr/navbars.less
This PR fixes an old bug about the top navbar toggle button position (mobile only) and align it on the grid/layout.
<kbd><img src="https://user-images.githubusercontent.com/15725/43730660-5b1bf98c-99ac-11e8-9a3e-fcdf2531fe1b.png" /></kbd>
<kbd><img src="https://user-images.githubusercontent.com/15725/43730761-b2941dc0-99ac-11e8-89e3-c5b4951d776b.png" /></kbd>
> Fix the navbar toggle button position

- .gitignore
- CHANGELOG.md
- package.json
- requirements/install.pip
- udata_gouvfr/theme/templates/admin.html
- webpack.config.js
This PR adds assets manifest support to the webpack build and 1.6 compatibility (adds `theme.css` to the `raw.html` template and `admin.css` to the `admin.html` template).
Connects to opendatateam/udata#1826
Tests won't pass until opendatateam/udata#1826 is merged (might require a CircleCI cache flush)
> Add assets manifest support

- CHANGELOG.md
- theme/less/gouvfr/cards.less
- theme/less/gouvfr/community.less
- theme/less/gouvfr/variables.less
Cf https://github.com/opendatateam/udata/pull/1884
ATM I kept the resource color (blue), any idea on a new one for discussions?
> Discussion add card style coherence

- CHANGELOG.md
- requirements/test.pip
- setup.cfg
- udata_gouvfr/tests.py
- udata_gouvfr/theme/__init__.py
- udata_gouvfr/theme/templates/home.html
This PR improves the Atom/RSS parsing and fixes multiple issues:
- parses both Atom and RSS 2.0
- supports missing thumbnail
- supports thumbnail from first image
- supports `srcset`/`sizes` attributes on `img` tags
- supports thumbnail as enclosure
- supports thumbnail as `media:rss` node
- this could be extracted as a themable last post from RSS/Atom widget into its own extensions
- for coherence, `WP_ATOM_URL` should be name `FEED_URL` or something more generic
- image size when available could be used to determinate the best image to display
> Improved RSS/Atom parsing

- CHANGELOG.md
- theme/less/gouvfr/cards.less
Il est du côté droit sur l'ensemble du site sauf dans les cartes.
> change le tampon de certification de place

- CHANGELOG.md
- udata_gouvfr/theme/templates/topic/display_base.html
see also: https://github.com/opendatateam/udata/pull/2171
> utilise `block related` pour ne rien mettre en pied de page

- CHANGELOG.md
- udata_gouvfr/templates/licences.html
The inclusion of the licence Ouverte 2.0 in the SPDX list
has been discussed here:
https://github.com/spdx/license-list-XML/issues/923
> Add SPDX short identifier for licence Ouverte 2.0

- CHANGELOG.md
- udata_gouvfr/__init__.py
- udata_gouvfr/theme/templates/home.html
C'est ce que j'ai trouvé de plus minimaliste et moins intrusif.
N'ayant pas encore réinstallé udata, c'est non testé par contre 🍿
> include external widget from recherche.etalab.studio

- CHANGELOG.md
- requirements/install.pip
- udata_gouvfr/settings.py
- udata_gouvfr/templates/page.html
- udata_gouvfr/tests/test_static_pages.py
- udata_gouvfr/tests/tests.py
- udata_gouvfr/views.py
This PR allows us to create, modify and crowdsource some static pages content on a GitHub repo. Every file named `pages/<slug>.md` in the repo will be available on `data.gouv.fr/pages/<slug>`. At the time being, the layout is similar to a post, eg https://www.data.gouv.fr/fr/posts/suivi-des-sorties-mai-2020/. It's possible to add linked datasets and reuses through frontmatter header:
```
---
title: Blogging Like a Hacker
keywords:
- test
- k2
- anapurna
description: yeah, described
reuses:
- 5eb2c6d45adcbd021d7b6cd5
datasets:
- depenses-d-assurance-maladie-hors-prestations-hospitalieres-donnees-nationales
---
```
Markdown on GitHub: https://github.com/abulte/datagouvfr-pages/blob/master/pages/keywords.md
> Add static /pages/* from md in github repo

- CHANGELOG.md
- udata_gouvfr/tests/test_static_pages.py
- udata_gouvfr/theme/__init__.py
- udata_gouvfr/views.py
This replaces #486 with a simpler solution: we will maintain a summary page of pages, so we only need one link in the footer and it does not need to be dynamic.
This also embeds the smarter caching for page content from #486.
Close #486.
> Add footer link to pages summary and page cache

- CHANGELOG.md
- udata_gouvfr/theme/templates/home.html
Changed the title of the elections inventory page in the homepage from "Données des ÉLECTIONS" to "Données relatives aux ÉLECTIONS", to have a uniform title convention. (merci Antonin)
> Changed inventory page title

- requirements/install.pip
Use v3.0.0.dev wheel from pypi.
Need to merge opendatateam/udata#2622 for wheel publication on remove-theme.
> WIP: Use pypi v3 wheel

- theme/less/layout/grid.less
For once, the PR is longer than the code it contains
> (refonte) Fix homepage for demo

- udata_gouvfr/tests/test_static_pages.py
- udata_gouvfr/tests/tests.py
- udata_gouvfr/theme/gouvfr/__init__.py
- udata_gouvfr/theme/gouvfr/templates/home.html
- udata_gouvfr/views/gouvfr.py
This PR:
- handles trailing slashes for static pages routing
- handles subdirectories routing for static pages
- cleans up unused views that have been migrated to static pages
Fix https://github.com/etalab/data.gouv.fr/issues/282
Fix https://github.com/etalab/data.gouv.fr/issues/289
> Fix /pages trailing slash + cleanup spd/licences views

- udata_gouvfr/theme/gouvfr/templates/home.html
Swapped the _comptes publics_ venti button for one to the [new _logement et urbanisme_ page](https://www.data.gouv.fr/fr/pages/donnees-logement-urbanisme). Colour is the same because of the limited palette in theme/less/content/colors.less
> Changed btn-venti to logement urbanisme

- udata_gouvfr/theme/gouvfr/templates/dataset/display.html
As a fix to #etalab/data.gouv.fr#238, remove link to user's page.
> Yet another link to a member page

- udata_gouvfr/theme/gouvfr/templates/dataset/display.html
Fix etalab/data.gouv.fr#326.
No particular treatment for main resources anymore.
> Set expanded to false for all resources

- CHANGELOG.md
- theme/js/components/search/search.vue
Fix https://github.com/etalab/data.gouv.fr/issues/346
Reset current page on search and suggestor change and on filters reset.
> Fix datasets search pagination reset

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/reuse/list.html
Fix https://github.com/etalab/data.gouv.fr/issues/336.
Need to make sure that other filters give appropriate results, ex: https://www.data.gouv.fr/en/reuses/?tag=machine-learning&followers=none.
> Fix for reuses filters type

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/home.html
Removed the venti button for the SPD and added the button for the new emploi inventory.
Colours have not been changed to stick with the palette https://github.com/etalab/udata-gouvfr/blob/master/theme/less/content/colors.less 
Mockup:
> Added emploi venti button

- CHANGELOG.md
- theme/js/components/search/search.vue
Fix https://github.com/etalab/data.gouv.fr/issues/404.
Query and page are linked to the url now, using the computed value `paramUrl` instead of facets only.
Maybe a better solution exists however.
> Fix dataset search params and link them to URL

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/dataset/resource/card.html
fix https://github.com/etalab/data.gouv.fr/issues/437
> Replace mdstrip filter with markdown in resources descriptions

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/home.html
Changed the first venti button in the home to link to the new santé inventory https://github.com/etalab/datagouvfr-pages/pull/31
The new santé inventory will have a link to the old COVID-19 inventory
~~Please merge only after publishing the inventory, i.e. when [etalab/datagouvfr-pages/pull/31](https://github.com/etalab/datagouvfr-pages/pull/31) is merged~~ ✅ ok to merge
> Added santé inventory venti button

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/dataset/display.html
Fix https://github.com/etalab/data.gouv.fr/issues/288.
Remove first duplicate block instead of second because community block seems like a footer because of it.
> Remove first duplicate participate block

- CHANGELOG.md
- theme/js/components/search/search-input.vue
- theme/js/components/search/suggest-box.vue
Fix https://github.com/etalab/data.gouv.fr/issues/371.
Any suggestion for a better pattern is welcome ! :)
> add onSubmit on suggest search input to redirect

- CHANGELOG.md
- udata_gouvfr/theme/gouvfr/templates/dataset/display.html
`geop:dataset_id` is more relevant and specific to geo.data.gouv.fr.
> Change banner trigger for geo.data.gouv.fr

- CHANGELOG.md
- udata_gouvfr/tests/views/test_organization.py
- udata_gouvfr/theme/gouvfr/templates/dataset/search-result.html
- udata_gouvfr/theme/gouvfr/templates/reuse/card.html
- udata_gouvfr/views/organization.py
Fix https://github.com/etalab/data.gouv.fr/issues/421 and https://github.com/etalab/data.gouv.fr/issues/420.
Show hidden datasets and reuses in same block as public ones.
For private datasets, a badge is shown.
Fix tests accordingly (and make empty assets explicit in those).
Ex:
> Show private datasets and reuses on organization page

- CHANGELOG.md
- udata_gouvfr/settings.py
- udata_gouvfr/tests/views/test_site.py
- udata_gouvfr/theme/gouvfr/templates/banners/generic.html
- udata_gouvfr/theme/gouvfr/templates/header.html
Make banner configurable (as previously existed with `BANNER_HTML_CONTENT` setting pre-refonte).
Questions:
- should we remove the subscription settings (`POST_BANNER_XXX` settings), currently unused ?
- won't the current content be too huge for a single setting and should we make it modular ? Not sure we can make something generic though.
We'll need to update the different playbooks accordingly (demo.data.gouv.fr is currently using the unused `BANNER_HTML_CONTENT`).
> Make banner configurable

- .circleci/config.yml
- CHANGELOG.md
Iterates on https://github.com/etalab/udata-gouvfr/pull/626.
When releasing, circle shouldn't try to push changes to .pip files (fixing `udata==x.x.x` for example)
> Don't commit deps changes in case of a tag build
