etalab/udata-gouvfr

udata_gouvfr/theme/theme.py
As a visitor, the aesthetic of the columns in the footer is awkward.
=> Refactor items in the footer, fixes #5

udata_gouvfr/theme/static/less/gouvfr.less, udata_gouvfr/theme/templates/dataset/display.html, udata_gouvfr/theme/templates/footer.html, udata_gouvfr/theme/templates/header.html, udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/templates/layouts/form.html, udata_gouvfr/theme/templates/metrics.html, udata_gouvfr/theme/templates/organization/display_base.html, udata_gouvfr/theme/templates/post/display.html, udata_gouvfr/theme/templates/reuse/display.html, udata_gouvfr/theme/templates/site/dashboard.html, udata_gouvfr/theme/templates/snippets/publish-action-modal.html, udata_gouvfr/theme/templates/topic/display_base.html
Depends on https://github.com/etalab/udata/pull/27
=> Improve performances (CPU, cache, memory)

udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/theme.py
Only add extra data to the home context. (Connects to etalab/udata#39)
=> Use the new home editorial mechanism

udata_gouvfr/templates/c3.html, udata_gouvfr/tests.py, udata_gouvfr/theme/theme.py, udata_gouvfr/views.py
=> Fixup on the C3 event

udata_gouvfr/templates/c3.html, udata_gouvfr/theme/templates/dataset/display.html, udata_gouvfr/views.py
Additionaly add "istrea" as a partner and sort datasets by popularity.
=> Add links to more datasets, fix etalab/udata#120

udata_gouvfr/templates/c3.html, udata_gouvfr/templates/dataconnexions.html, udata_gouvfr/theme/templates/footer.html, udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/templates/subnav-large.html, udata_gouvfr/theme/templates/subnav-small.html
This pull request cache some jinja snippets.
=> Cache improvements

udata_gouvfr/harvesters/maaf.py
This pull-request update the maff harvester with latest udata-harvest feature.
Depends on etalab/udata-harvest#5
=> Update maaf harvester

travis.pip, udata_gouvfr/harvesters/maaf.py, udata_gouvfr/tests.py, udata_gouvfr/theme/templates/dataset/display.html, udata_gouvfr/theme/templates/snippets/publish-action-modal.html
This pull request adjust this extensions for etalab/udata#144
=> Admin harvest merge

theme/less/gouvfr/community.less
Add the appropriated style for community resources.
=> Make check URL more clever, refs #170

udata_gouvfr/theme/templates/dataset/display.html
No translations are required given that I reuse existing strings.
=> Fix the link to create a new community resource

theme/less/gouvfr/typeahead.less
=> fixed oversized searchbox result with max-width. Fix #59

udata_gouvfr/harvesters/maaf.py
This PR fix a side effect of renaming resource.type into resource.filetype.
=> Fix maaf harvester resources handling

udata_gouvfr/templates/faq/developer.html, udata_gouvfr/theme/templates/macros/integrate.html
=> Document cards integration, refs etalab/udata#268

udata_gouvfr/templates/dataconnexions-5.html, udata_gouvfr/templates/dataconnexions-6.html, udata_gouvfr/theme/templates/footer.html, udata_gouvfr/theme/templates/header.html, udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/templates/layouts/center-panel.html, udata_gouvfr/theme/templates/macros/integrate.html, udata_gouvfr/theme/templates/organization/sidebar-producer.html, udata_gouvfr/theme/templates/subnav-large.html, udata_gouvfr/theme/templates/subnav-small.html, udata_gouvfr/theme/templates/topic/subnav.html
For description: https://github.com/etalab/udata/pull/339
=> HTML5 validation, refs etalab/udata#338

udata_gouvfr/models.py, udata_gouvfr/templates/faq/home.html, udata_gouvfr/theme/templates/footer.html
See https://github.com/etalab/udata/issues/341 for description.
=> Improve territories rendering, refs etalab/udata#341

udata_gouvfr/templates/faq/base.html, udata_gouvfr/theme/info.json, udata_gouvfr/theme/theme.py, udata_gouvfr/views.py
Work based on https://github.com/etalab/udata-gouvfr/pull/73
=> GitHub edit links to edit/enhance the FAQ

udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/theme.py
This PR comes after #85 to totally drop theme config
=> Drop theme config

udata_gouvfr/theme/templates/subnav-small.html
=> Search only for a given zone when in town context

package.json, setup.cfg, tasks.py, udata_gouvfr/__init__.py, udata_gouvfr/harvesters/__init__.py, udata_gouvfr/harvesters/maaf.py, udata_gouvfr/tests.py, udata_gouvfr/theme/theme.py, udata_gouvfr/views.py
This PR apply the same modification than https://github.com/etalab/udata/pull/426 :
- fix the `TERRITORY_DATASETS` usage.
- fix the flake8 lints
- make use of npm run-scripts
=> Python lints

udata_gouvfr/migrations/2016-04-05-deactivate-datapublica.js
=> Deactivate datasets for Banque Mondiale and Eurostat

udata_gouvfr/models.py, udata_gouvfr/tests.py
=> Add addresses dataset to towns, fix etalab/udata#435

udata_gouvfr/theme/templates/header.html
=> Apply required change for Flask-Login 0.3+

udata_gouvfr/models.py, udata_gouvfr/tests.py
=> Add licenses and sources to embeds

theme/less/gouvfr-forms.less
Required for the YouCKAN replacement.
=> Padding for register form

travis.dev.pip, travis.master.pip
This PR apply udata repository url change
=> Change udata repository

udata_gouvfr/models.py, udata_gouvfr/tests.py, udata_gouvfr/theme/templates/subnav-small.html, udata_gouvfr/theme/theme.py
See https://github.com/opendatateam/udata/pull/467
=> Add counties to territories, refs opendatateam/udata#466

udata_gouvfr/templates/faq/developer.html
I know that we are on our way to document that probably elsewhere but I prefer to keep the current doc in sync with the code.
=> Document the ability to embed orgs, refs opendatateam/udata#495

tasks.py
This PR is connected to opendatateam/udata#507
=> Port tasks to invoke 0.13

theme/less/gouvfr-org.less, udata_gouvfr/theme/templates/home.html, udata_gouvfr/theme/templates/macros/integrate.html
This PR is connected to opendatateam/udata#508
=> Drop bootstrap tooltips and use tooltip directive everywhere

udata_gouvfr/templates/openfield16.html, udata_gouvfr/tests.py
=> Openfield16 v2

babel.cfg
Follow opendatateam/udata#556 changes
=> Upgraded the discontinued flask-cache to flask-caching 1.0.1

udata_gouvfr/tests.py, udata_gouvfr/theme/theme.py
This PR adds error handling (failsafe) on WP Atom retrieval
=> WP Atom error handling

bumpr.rc
This adds a bumpr configuration for painless releases
=> Added bumpr configuration

CHANGELOG.md, README.md, bumpr.rc, circleci-requirements.sh, circleci.dev.pip, circleci.master.pip, setup.py
=> Merge current master into dev

theme/less/gouvfr/site-search.less
This PR, combined with opendatateam/udata#748, fix #149 (gouvfr home page is a special case and should be handled as it is)
=> Special case handling for subnav large site search (fix #149)

theme/less/gouvfr/site-search.less, udata_gouvfr/theme/templates/subnav-large.html, udata_gouvfr/theme/templates/subnav-small.html, udata_gouvfr/theme/templates/topic/subnav.html
Related to opendatateam/udata#752
=> Make use of site_search macro

theme/less/gouvfr-dashboard.less, theme/less/gouvfr-org.less
Related to opendatateam/udata#758
This PR only fix spinner color in community section.
=> Fixes related to opendatateam/udata#758

udata_gouvfr/theme/theme.py
Drop the following header menu item:
- events
- CADA
- Etalab
=> Lightweight header menu

CHANGELOG.md, udata_gouvfr/tests.py, udata_gouvfr/views.py
=> Ensure a 404 is raised for unknown FAQ sections (fix #156)

theme/less/gouvfr-dataset.less, theme/less/gouvfr-post.less, theme/less/gouvfr-reuse.less, theme/less/gouvfr.less, theme/theme.js, udata_gouvfr/templates/dataconnexions-5.html, udata_gouvfr/templates/dataconnexions-6.html, udata_gouvfr/theme/templates/footer.html, udata_gouvfr/theme/templates/macros/integrate.html, udata_gouvfr/theme/templates/organization/sidebar-producer.html
This PR is related to opendatateam/udata#828:
- apply same changes (popover...)
- fixes some styles to adapt these changes
- removed some style breaking in views
=> Drop legacy widgets

CHANGELOG.md, udata_gouvfr/models.py, udata_gouvfr/templates/spd.html, udata_gouvfr/tests.py, udata_gouvfr/views.py
This PR introduce the SPD page and badge.
Right now, this is only the skeleton.
=> [WIP] SPD page

udata_gouvfr/templates/spd.html, udata_gouvfr/views.py
* change the route to /reference
* 2-columns layout
* fix a few typos
=> Iteration on the draft SPD page

theme/less/gouvfr.less, theme/less/gouvfr/spd.less, udata_gouvfr/templates/spd.html
Same content but with a layout inspired from the one used in contests (gray datasets list, context on right...)
=> New layout proposal for SPD page

udata_gouvfr/templates/spd.html
Fix 2 small typos spotted by LL
=> Fix typos in SPD page

CHANGELOG.md, theme/less/gouvfr/community.less, udata_gouvfr/theme/templates/home.html
Ajustment for the jquery-dotdotdot removal. See opendatateam/udata#853
=> Ajustment for the jquery-dotdotdot removal

CHANGELOG.md, setup.py, udata_gouvfr/harvesters/maaf.py
This PR exposes the maaf harvester as an entrypoint.
See opendatateam/udata#1004
=> Use the udata.harvesters entrypoint

CHANGELOG.md, udata_gouvfr/theme/templates/footer.html
=> Change footer label from 'Contacts' to 'Contact Us'

README.md, setup.py
This PR actualize the README and distinguish installation and development
=> Refactor README and split installation and development

CHANGELOG.md, theme/less/gouvfr/community.less
Counterpart of https://github.com/opendatateam/udata/pull/1288
=> Export community resource avatar style to udata

.circleci/config.yml, .circleci/requirements.pip, .gitignore, CHANGELOG.md, requirements/develop.pip, requirements/install.pip, requirements/test.pip, setup.cfg, setup.py, tasks.py, udata_gouvfr/metrics.py, udata_gouvfr/tests.py
This PR is connected to opendatateam/udata#1400 and switch to pytest too.
It update deprecated dependencies and tooling by the same way.
=> Update tooling and switch to pytest

CHANGELOG.md, theme/less/gouvfr.less
This PR connects to opendatateam/udata#1410 and apply coherent changes on search page
| Before | After |
|-----------|--------|
| ![screenshot-data xps-2018-01-29-21-54-31-162](https://user-images.githubusercontent.com/15725/35554797-44691150-059d-11e8-85fe-9b949074d09e.png) | ![screenshot-data xps-2018-01-29-21-50-34-623](https://user-images.githubusercontent.com/15725/35554804-495752d0-059d-11e8-8713-3a74ee1d886f.png) |
| Before | After |
|-----------|--------|
| ![screenshot-data xps-2018-01-29-21-54-53-152](https://user-images.githubusercontent.com/15725/35554815-53638df2-059d-11e8-97d1-7570c237a954.png) | ![screenshot-data xps-2018-01-29-21-51-04-784](https://user-images.githubusercontent.com/15725/35554819-59615004-059d-11e8-91ce-cae05a9028d7.png) |
=> Adjust search facets badges

CHANGELOG.md, requirements/install.pip, setup.cfg, setup.py, tasks.py, udata_gouvfr/__init__.py, udata_gouvfr/theme/babel.cfg, udata_gouvfr/theme/translations/es/LC_MESSAGES/gouvfr.po, udata_gouvfr/theme/translations/fr/LC_MESSAGES/gouvfr.po, udata_gouvfr/theme/translations/gouvfr.pot, udata_gouvfr/translations/es/LC_MESSAGES/udata-gouvfr.po, udata_gouvfr/translations/fr/LC_MESSAGES/udata-gouvfr.po, udata_gouvfr/translations/udata-gouvfr.pot
This PR properly split plugins translations and theme translation (first step to using each others separately) and expose new entrypoints.
Connects to opendatateam/udata#1431
=> New entrypoints

CHANGELOG.md, theme/less/gouvfr-dataset.less, theme/less/gouvfr-home.less, theme/less/gouvfr-topic.less, theme/less/gouvfr.less, theme/less/gouvfr/community.less, theme/less/gouvfr/navbars.less, theme/less/gouvfr/resources.less, udata_gouvfr/theme/templates/home.html
CF opendatateam/udata#1383
Same as #228 but keep the carousel
=> Align cards style (alt)

CHANGELOG.md, udata_gouvfr/tests.py, udata_gouvfr/theme/__init__.py
=> Discourse timeout and response parse error catch

CHANGELOG.md, udata_gouvfr/theme/templates/home.html
=> Tracking of carousel efficiency

.circleci/config.yml, theme/less/gouvfr.less
Move fix to opendatateam/udata#1477
=> Move search results fixes to upstream

CHANGELOG.md, udata_gouvfr/theme/templates/carousel.html, udata_gouvfr/theme/templates/home.html
=> temporary carousel layout

theme/less/gouvfr.less, theme/less/gouvfr/mixins.less
Connects to opendatateam/udata#1479
=> Fix line clamping

CHANGELOG.md, theme/less/gouvfr-dataset.less
Related to https://github.com/opendatateam/udata/pull/1435
=> Typed resources related styles

CHANGELOG.md, udata_gouvfr/migrations/2018-04-09-normalize-resource-filetype.js
Related to https://github.com/opendatateam/udata/pull/1567
=> Enforce a domain whitelist when resource.filetype is file (migration)

.gitignore, CHANGELOG.md, udata_gouvfr/migrations/2018-04-18-migrate-active-users.js
=> Ensure active users have a confirmed_at date

.circleci/config.yml, requirements/install.pip, udata_gouvfr/tests.py
Apply test changes from opendatateam/udata#1768
Connects to opendatateam/udata#1768
Connects to #316
=> Switch to local.test

CHANGELOG.md, theme/less/gouvfr/site-search.less
=> Fix the multisearch labels position

CHANGELOG.md, setup.py, theme/less/gouvfr/site-search.less
This PR backports #330 to the `1.4` branch and add Python version specifier in `setup.py`
=> Backport fixes on 1.4

.circleci/config.yml, .gitignore, CHANGELOG.md, package.json, requirements/develop.pip, requirements/test.pip, setup.py, theme/less/gouvfr/navbars.less, theme/less/gouvfr/site-search.less, udata_gouvfr/templates/spd.html, udata_gouvfr/theme/templates/admin.html, webpack.config.js
Merge current `master` into `py3` branch
=> Python 3 - Merge master

CHANGELOG.md, theme/less/gouvfr-dataset.less
Connects to opendatateam/udata#1893
=> Remove a duplicate rule

CHANGELOG.md, udata_gouvfr/models.py
À usage de l'équipe Adresse d'Etalab.
En attendant d'avoir des mots-clés utilisateur :)
=> Ajout du badge BAL

CHANGELOG.md, udata_gouvfr/theme/templates/security/register_user.html
=> remove extra TOS

package.json, theme/js/henri.js, udata_gouvfr/theme/templates/home.html, webpack.config.js
=> Add konami code for H.

CHANGELOG.md, udata_gouvfr/templates/licences.html
Reverts etalab/udata-gouvfr#364
A little too soon for that according to our lawyers.
=> Revert "Remove BAN license"

CHANGELOG.md, udata_gouvfr/models.py, udata_gouvfr/tests.py
Fix https://github.com/etalab/data.gouv.fr/issues/120
=> Remove "compte des collectivités" from territories

CHANGELOG.md, theme/less/gouvfr-topic.less, udata_gouvfr/theme/templates/topic/display.html, udata_gouvfr/theme/templates/topic/display_base.html, udata_gouvfr/theme/templates/topic/subnav.html
- no more carrousel
- no more CTA
- move related tags upward
=> Quick update of topics UI

CHANGELOG.md, requirements/install.pip, requirements/test.pip
Should allow merging https://github.com/etalab/udata-gouvfr/pull/388
=> pin same version of requests than udata

udata_gouvfr/theme/__init__.py, udata_gouvfr/theme/translations/fr/LC_MESSAGES/gouvfr.po
Cette _pull-request_ change le texte du premier onglet affiché sous la Mariane, pour mieux refléter ce vers quoi il redirige, à savoir : https://doc.data.gouv.fr/ — la documentation de https://www.data.gouv.fr.
=> Renomme Découvrez l’OpenData en Documentation

CHANGELOG.md, udata_gouvfr/theme/templates/subnav-small.html
=> remove contribute and topic chooser from search bar

CHANGELOG.md, udata_gouvfr/theme/templates/topic/display_base.html
Related to https://github.com/opendatateam/udata/pull/2194
=> Add cache for topic display page

CHANGELOG.md, udata_gouvfr/theme/__init__.py
Cf https://github.com/opendatateam/udata/pull/2195
=> Data catalog: id as ref instead of slug

CHANGELOG.md, udata_gouvfr/theme/templates/dataset/display.html
FIX https://github.com/etalab/udata-gouvfr/issues/416
=> Aligne la taille des cartes

CHANGELOG.md, package.json, theme/js/henri.js, udata_gouvfr/theme/templates/home.html, webpack.config.js
=> Suppression du konami code

CHANGELOG.md, udata_gouvfr/theme/__init__.py
Cf https://github.com/opendatateam/udata/pull/2343
=> Link to external API doc in footer

udata_gouvfr/views.py
Fix https://sentry.data.gouv.fr/etalab/demo-datagouvfr/issues/1883989/
=> Protect pages lookup from ValidationError

udata_gouvfr/templates/licences.html
See https://www.gnu.org/licenses/identify-licenses-clearly.en.html.
=> licences.html: Update GNU licenses to their "or-later" versions

theme/less/gouvfr/banners.less, udata_gouvfr/theme/templates/dataset/display.html, udata_gouvfr/theme/templates/header.html
Cf https://github.com/opendatateam/udata/pull/2565
=> WIP: Read only mode modification for theme

theme/less/gouvfr/banners.less, udata_gouvfr/theme/templates/dataset/display.html, udata_gouvfr/theme/templates/header.html
Reverts etalab/udata-gouvfr#505
=> Revert "Read only mode modification for theme"

CHANGELOG.md, theme/less/gouvfr.less, theme/less/gouvfr/alerts.less, udata_gouvfr/settings.py, udata_gouvfr/theme/templates/post/list.html
fix https://github.com/etalab/data.gouv.fr/issues/191
=> Add newsletter's subscription banner

CHANGELOG.md, udata_gouvfr/theme/__init__.py, udata_gouvfr/theme/translations/gouvfr.pot, udata_gouvfr/translations/udata-gouvfr.pot
fix https://github.com/etalab/data.gouv.fr/issues/193
=> Add dropdown for etalab guides

CHANGELOG.md, udata_gouvfr/theme/__init__.py, udata_gouvfr/theme/templates/footer.html
fix https://github.com/etalab/data.gouv.fr/issues/203
=> Add link to support page

udata_gouvfr/theme/gouvfr/templates/security/change_password.html, udata_gouvfr/theme/gouvfr/templates/security/forgot_password.html, udata_gouvfr/theme/gouvfr/templates/security/login_user.html, udata_gouvfr/theme/gouvfr/templates/security/register_user.html, udata_gouvfr/theme/gouvfr/templates/security/reset_password.html, udata_gouvfr/theme/gouvfr/templates/security/send_confirmation.html
=> Remove incorrect cache on security pages

udata_gouvfr/theme/gouvfr/templates/territories/commune.html, udata_gouvfr/theme/gouvfr/templates/territories/departement.html, udata_gouvfr/theme/gouvfr/templates/territories/home.html, udata_gouvfr/theme/gouvfr/templates/territories/region.html, udata_gouvfr/theme/gouvfr/templates/territories/territory.html
Fix etalab/data.gouv.fr#209
I think the disclaimer message might need more work tho
=> (territories) Fixes territories pages display and adds a disclaimer banner

udata_gouvfr/theme/gouvfr/templates/territories/home.html, udata_gouvfr/theme/gouvfr/templates/territories/territory.html
=> (territories) @abulte fix broke my fix

theme/js/plugins/i18n.js, udata_gouvfr/theme/gouvfr/templates/dataset/display.html, udata_gouvfr/theme/gouvfr/templates/header.html, udata_gouvfr/theme/gouvfr/templates/organization/display.html, udata_gouvfr/theme/gouvfr/templates/reuse/display.html, udata_gouvfr/theme/gouvfr/templates/security/change_password.html, udata_gouvfr/theme/gouvfr/templates/security/forgot_password.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Update .pot file accordingly.
Also load fr locale in JS.
=> Fix translations errors (content in French, newlines)

theme/js/components/search/search.vue, udata_gouvfr/theme/gouvfr/templates/oembed.html
PR baroud d'honneur avant de partir
=> Feat/bugfixes 2.2

udata_gouvfr/theme/gouvfr/__init__.py, udata_gouvfr/theme/gouvfr/templates/footer.html
Close etalab/data.gouv.fr#303.
Waiting for etalab/datagouvfr-pages#27.
Update translations only after.
=> Add accessibility and etalab licence link

package-lock.json, theme/less/specific/header.less, udata_gouvfr/theme/gouvfr/templates/header.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Fix https://github.com/etalab/data.gouv.fr/issues/296
TODO: iterate on wording, fink a link for "apprenez-en plus" @agarrone 
Nice to have: click to dismiss (but it goes away when scrolling down on mobile).
=> Bandeau beta

theme/js/components/discussions/avatar.vue, udata_gouvfr/theme/gouvfr/templates/dataset/display.html, udata_gouvfr/theme/gouvfr/templates/organization/producer-panel.html, udata_gouvfr/theme/gouvfr/templates/reuse/display.html
Fix etalab/data.gouv.fr#238.
Remove any link to member pages.
=> Remove links to member page

udata_gouvfr/theme/gouvfr/templates/macros/paginator.html, udata_gouvfr/theme/gouvfr/templates/organization/display.html, udata_gouvfr/views/organization.py
Fix https://github.com/etalab/data.gouv.fr/issues/309
=> Pagination on org page

theme/js/components/search/suggest-results.vue, theme/js/locales/en.json, theme/js/locales/es.json, theme/js/locales/fr.json, udata_gouvfr/theme/gouvfr/templates/dataset/display.html, udata_gouvfr/theme/gouvfr/templates/reuse/display.html, udata_gouvfr/theme/gouvfr/templates/security/login_user.html, udata_gouvfr/theme/gouvfr/templates/security/register_user.html, udata_gouvfr/theme/gouvfr/templates/security/reset_password.html, udata_gouvfr/theme/gouvfr/templates/security/send_confirmation.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Close etalab/data.gouv.fr#266
Fix etalab/data.gouv.fr#273
Translations will be extracted in another PR to prevent conflicts.
=> Replace lorem ipsum by explanation texts

theme/js/locales/en.json, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Iterate on etalab/data.gouv.fr#315.
Need to set en.json translation value manually (value is empty by default, even for en. Will improve later, https://github.com/etalab/data.gouv.fr/projects/4#card-64214465).
=> Update extracted translation strings

theme/js/components/dataset/schema-modal.vue, udata_gouvfr/settings.py, udata_gouvfr/theme/gouvfr/templates/dataset/resource/schema-button.html
Also add some missing settings from `udata-schemagouvfr`, fix `authorize_validation` casting to Boolean.
Fix https://github.com/etalab/data.gouv.fr/issues/325
=> Style schema modal

CHANGELOG.md, theme/js/components/dataset/search-result.vue, udata_gouvfr/theme/gouvfr/templates/dataset/search-result.html
fix https://github.com/etalab/data.gouv.fr/issues/317
=> Fix resources number in dataset preview

udata_gouvfr/theme/gouvfr/templates/organization/display.html
Fix https://github.com/etalab/data.gouv.fr/issues/330
=> Fix counts on org page

udata_gouvfr/theme/gouvfr/templates/dataset/display.html
Fix etalab/data.gouv.fr#292.
dataset/resource/card.html were included twice.
=> Remove duplicate community resource

udata_gouvfr/theme/gouvfr/templates/footer.html
Fix https://github.com/etalab/data.gouv.fr/issues/283.
Not clean cause we don't replace using a regex instead of using the current locale.
=> Connect language selector

theme/js/components/search/search.vue
Fix https://github.com/etalab/data.gouv.fr/issues/346.
Change pagination query param to the correct one.
=> Fix datasets search pagination

CHANGELOG.md
Forgot to update changelog in #585
=> Update changelog with pagination fix

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/header.html
Fix https://github.com/etalab/data.gouv.fr/issues/355.
=> Replace last /search href by /datasets

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/header.html
Fix https://github.com/etalab/data.gouv.fr/issues/360.
=> Remove suggest mobile

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/dataset/list.html, udata_gouvfr/theme/gouvfr/templates/organization/list.html
Close https://github.com/etalab/data.gouv.fr/issues/354.
Just wanted to estimate feature request dev time, seemed to go very smoothly thanks to @gmougeolle reusable components!
=> Add organization search

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/dataset/resource/card.html
fix https://github.com/etalab/data.gouv.fr/issues/364
=> Fix resources description

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/home.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Close https://github.com/etalab/data.gouv.fr/issues/363.
Need to add translations on crowdin after merge before deployment.
=> Add all featured topics button on homepage

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/home.html, udata_gouvfr/views/site.py
Fix https://github.com/etalab/data.gouv.fr/issues/333
=> Add SPD datasets to home page

CHANGELOG.md, package-lock.json, theme/less/components/well.less, udata_gouvfr/theme/gouvfr/templates/dataset/display.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
When a dataset comes from geo.data.gouv.fr:
- the banner below is shown
- `noindex, nofollow` is added to the metas
=> Banner for geo.data.gouv.fr shutdown

udata_gouvfr/theme/gouvfr/templates/header.html, udata_gouvfr/theme/gouvfr/templates/home.html, udata_gouvfr/theme/gouvfr/templates/security/change_password.html, udata_gouvfr/theme/gouvfr/templates/security/forgot_password.html, udata_gouvfr/theme/gouvfr/templates/security/login_user.html, udata_gouvfr/theme/gouvfr/templates/security/reset_password.html, udata_gouvfr/theme/gouvfr/templates/territories/territory.html, udata_gouvfr/theme/gouvfr/templates/topic/display.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
English wording for https://github.com/etalab/data.gouv.fr/issues/415.
Will still need to update French translations accordingly in crowdin.
=> Homepage wording

CHANGELOG.md, udata_gouvfr/theme/gouvfr/__init__.py
Close https://github.com/etalab/data.gouv.fr/issues/455.
Relevant pages: 
- https://github.com/etalab/datagouvfr-pages/blob/master/pages/about/a-propos.md
- https://github.com/etalab/datagouvfr-pages/blob/master/pages/about/opendata.md
=> Add about in header

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/user/base.html, udata_gouvfr/theme/gouvfr/translations/gouvfr.pot
Close https://github.com/etalab/data.gouv.fr/issues/389.
=> Show profile in admin for sysadmin

CHANGELOG.md, udata_gouvfr/theme/gouvfr/templates/organization/display.html
fix https://github.com/etalab/data.gouv.fr/issues/367
=> Remove sort by button on organization age
